### ISSUE TITLE
miq shell broken after #5084

### ISSUE THREAD

**Issue by jkrocil** [ManageIQ/integration_tests#5102]
```
(cfme_env)[jkrocil@zephyros cfme_tests]$ miq
Traceback (most recent call last):
  File "/home/jkrocil/Workspace/venvs/cfme_env/bin/miq", line 11, in <module>
    load_entry_point('manageiq-integration-tests', 'console_scripts', 'miq')()
  File "/home/jkrocil/Workspace/venvs/cfme_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jkrocil/Workspace/venvs/cfme_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2652, in load_entry_point
    return ep.load()
  File "/home/jkrocil/Workspace/venvs/cfme_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2306, in load
    return self.resolve()
  File "/home/jkrocil/Workspace/venvs/cfme_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jkrocil/Workspace/cfme_tests/cfme/scripting/miq.py", line 6, in <module>
    from scripts.dockerbot.sel_container import main as sel_con_main
ImportError: cannot import name main

```
