### ISSUE TITLE
E       TypeError: __init__() got an unexpected keyword argument 'prov_class'

### ISSUE THREAD

**Issue by jaryn** [ManageIQ/integration_tests#7606]
I am getting this error on 3ec95dd518d28b8

```
>       network_provider = collection.all()[0]

cfme/tests/networks/test_sdn_inventory_collection.py:132: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cfme/networks/provider/__init__.py:294: in all
    provider=self.filters.get('provider')))
cfme/modeling/base.py:119: in instantiate
    return self.ENTITY.from_collection(self, *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'cfme.networks.provider.NetworkProvider'>
collection = NetworkProviderCollection(filters={'provider': AzureProvider(endpoints={'defau...d-8922-c9b8e2c3f100', subscription_id='c9e72ccc-b20e-48bd-a0c8-879c6dbcbfbb')})
k = ()
kw = {'name': 'azure Network Manager', 'prov_class': <class 'cfme.networks.provider.NetworkProvider'>, 'provider': AzurePro...cloud.provider.azure.AzureEndpoint o...0ed-8922-c9b8e2c3f100', subscription_id='c9e72ccc-b20e-48bd-a0c8-879c6dbcbfbb')}

    @classmethod
    def from_collection(cls, collection, *k, **kw):
>       return cls(collection, *k, **kw)
E       TypeError: __init__() got an unexpected keyword argument 'prov_class'
```

I found out it has been introduced with 0284b75a90

**Comment by digitronik** [comment]
This is not due to https://github.com/ManageIQ/integration_tests/commit/0284b75a90cbe8fe0df3ecc1c49a4d4b3440d5f8. It due to some small changes https://github.com/ManageIQ/integration_tests/commit/a7eb2be4d3d7e2c93959c94cf7c640971e78b877#diff-3a42131a513df7d23cac5a7c9c9b33d5L304
Fixing this issue.... for `all()` method.
