### PR TITLE
[1LP][RFR] Change from isort to reorder-python-imports

### LINKED ISSUE #8485: Move from isort to reorder_imports
isort + seed_isort has caused repeated issues for contributors that have not modified the requirements files or the isort cfg file in travis.

### PR DESCRIPTION
**Pull request by mshriver**
Remove .isort.cfg (preseed for isort)
Update .pre-commit-config.yaml to use reorder-python-imports
Apply import reorder to repo

FIXES #8485 

Added a bunch of reviewers because I would like to get some feedback on the style used for imports.  This will change our single-line imports from the same module to separate lines, which will reduce merge conflicts when imports change.

We have had several people hit issues with .isort.cfg failing pre-commit hooks, when they have made no changes to .isort.cfg in their commits, and have not changed the requirement files at all.  Following @RonnyPfannschmidt suggestion to drop to reorder-python-imports, as it is not pre-seeded. 

NOTE:

Travis runs pre-commit in py3.6, and it appears that the sort order is changed between py2.7 and py3.6. This will likely cause some confusion for those working in a py2.7 env that then see travis fail. We are starting to prioritize our move to py3.6+ due to the mounting challenges in dealing with both versions.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 81c2acfc98602bb5e24fda5211006061009d7736:

`cfme/common/provider_views.py`:
- :red_circle: Line 17:1: **F811** *redefinition of unused 'Accordion' from line 8*

`cfme/control/__init__.py`:
- :red_circle: Line 1:1: **F401** *'.explorer' imported but unused*
- :red_circle: Line 2:1: **F401** *'.import_export' imported but unused*
- :red_circle: Line 3:1: **F401** *'.log' imported but unused*
- :red_circle: Line 4:1: **F401** *'.simulation' imported but unused*

`cfme/fixtures/appliance.py`:
- :red_circle: Line 18:1: **F401** *'cfme.utils.version.get_stream' imported but unused*

`cfme/infrastructure/virtual_machines.py`:
- :red_circle: Line 22:1: **F401** *'widgetastic_patternfly.BootstrapNav' imported but unused*

`cfme/services/service_catalogs/ssui.py`:
- :red_circle: Line 6:1: **F401** *'widgetastic_patternfly.BootstrapSelect' imported but unused*
- :red_circle: Line 8:1: **F401** *'widgetastic_patternfly.Input' imported but unused*

`cfme/storage/volume_type.py`:
- :red_circle: Line 4:1: **F401** *'navmazing.NavigateToSibling' imported but unused*
- :red_circle: Line 5:1: **F401** *'widgetastic.widget.NoSuchElementException' imported but unused*

`cfme/tests/cloud/test_providers.py`:
- :red_circle: Line 20:1: **F401** *'cfme.common.provider_views.CloudProvidersDiscoverView' imported but unused*
- :red_circle: Line 31:1: **F401** *'cfme.utils.rest.delete_resources_from_collection' imported but unused*
- :red_circle: Line 32:1: **F401** *'cfme.utils.rest.delete_resources_from_detail' imported but unused*

`cfme/tests/configure/test_log_depot_operation.py`:
- :red_circle: Line 9:1: **F401** *'datetime.timedelta' imported but unused*

`cfme/tests/configure/test_schedule_operations.py`:
- :red_circle: Line 10:1: **F401** *'cfme.utils.conf' imported but unused*

`cfme/tests/containers/test_alerts.py`:
- :red_circle: Line 6:1: **F401** *'cfme.utils.version.current_version' imported but unused*

`cfme/tests/infrastructure/test_pxe_provisioning.py`:
- :red_circle: Line 13:1: **F401** *'cfme.utils.blockers.BZ' imported but unused*
- :red_circle: Line 14:1: **F401** *'cfme.utils.blockers.GH' imported but unused*

`cfme/tests/openstack/cloud/test_volumes.py`:
- :red_circle: Line 10:1: **F401** *'cfme.utils.wait.wait_for' imported but unused*

`cfme/tests/openstack/infrastructure/test_hosts.py`:
- :red_circle: Line 5:1: **F401** *'cfme.utils.appliance.implementations.ui.navigator' imported but unused*

`cfme/tests/services/test_rest_services.py`:
- :red_circle: Line 13:1: **F401** *'cfme.rest.gen_data.blueprints as _blueprints' imported but unused*

`cfme/tests/test_db_migrate.py`:
- :red_circle: Line 7:1: **F401** *'cfme.utils.conf' imported but unused*

`cfme/utils/browser.py`:
- :red_circle: Line 7:1: **F401** *'warnings' imported but unused*

`cfme/utils/version.py`:
- :red_circle: Line 6:1: **F401** *'miq_version.LATEST' imported but unused*
- :red_circle: Line 7:1: **F401** *'miq_version.LOWEST' imported but unused*
- :red_circle: Line 8:1: **F401** *'miq_version.SPTuple' imported but unused*
- :red_circle: Line 9:1: **F401** *'miq_version.UPSTREAM' imported but unused*
- :red_circle: Line 11:1: **F401** *'miq_version.version_stream_product_mapping' imported but unused*

`cfme/utils/wait.py`:
- :red_circle: Line 3:1: **F401** *'wait_for.RefreshTimer' imported but unused*
- :red_circle: Line 4:1: **F401** *'wait_for.TimedOutError' imported but unused*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
I will rebase and clean up the lint "unused imports", but they don't impact the core changes if people want to weigh in.

**Comment by dajoRH** [comment]
Lint report for commit 2de48471b6d48df0accc7605644d839da6768ee4:

`cfme/common/provider_views.py`:
- :red_circle: Line 17:1: **F811** *redefinition of unused 'Accordion' from line 8*

`cfme/control/__init__.py`:
- :red_circle: Line 1:1: **F401** *'.explorer' imported but unused*
- :red_circle: Line 2:1: **F401** *'.import_export' imported but unused*
- :red_circle: Line 3:1: **F401** *'.log' imported but unused*
- :red_circle: Line 4:1: **F401** *'.simulation' imported but unused*

`cfme/fixtures/appliance.py`:
- :red_circle: Line 18:1: **F401** *'cfme.utils.version.get_stream' imported but unused*

`cfme/infrastructure/virtual_machines.py`:
- :red_circle: Line 22:1: **F401** *'widgetastic_patternfly.BootstrapNav' imported but unused*

`cfme/services/service_catalogs/ssui.py`:
- :red_circle: Line 6:1: **F401** *'widgetastic_patternfly.BootstrapSelect' imported but unused*
- :red_circle: Line 8:1: **F401** *'widgetastic_patternfly.Input' imported but unused*

`cfme/storage/volume_type.py`:
- :red_circle: Line 4:1: **F401** *'navmazing.NavigateToSibling' imported but unused*
- :red_circle: Line 5:1: **F401** *'widgetastic.widget.NoSuchElementException' imported but unused*

`cfme/tests/cloud/test_providers.py`:
- :red_circle: Line 20:1: **F401** *'cfme.common.provider_views.CloudProvidersDiscoverView' imported but unused*
- :red_circle: Line 31:1: **F401** *'cfme.utils.rest.delete_resources_from_collection' imported but unused*
- :red_circle: Line 32:1: **F401** *'cfme.utils.rest.delete_resources_from_detail' imported but unused*

`cfme/tests/configure/test_log_depot_operation.py`:
- :red_circle: Line 9:1: **F401** *'datetime.timedelta' imported but unused*

`cfme/tests/configure/test_schedule_operations.py`:
- :red_circle: Line 10:1: **F401** *'cfme.utils.conf' imported but unused*

`cfme/tests/containers/test_alerts.py`:
- :red_circle: Line 6:1: **F401** *'cfme.utils.version.current_version' imported but unused*

`cfme/tests/infrastructure/test_pxe_provisioning.py`:
- :red_circle: Line 13:1: **F401** *'cfme.utils.blockers.BZ' imported but unused*
- :red_circle: Line 14:1: **F401** *'cfme.utils.blockers.GH' imported but unused*

`cfme/tests/openstack/cloud/test_volumes.py`:
- :red_circle: Line 10:1: **F401** *'cfme.utils.wait.wait_for' imported but unused*

`cfme/tests/openstack/infrastructure/test_hosts.py`:
- :red_circle: Line 5:1: **F401** *'cfme.utils.appliance.implementations.ui.navigator' imported but unused*

`cfme/tests/services/test_rest_services.py`:
- :red_circle: Line 13:1: **F401** *'cfme.rest.gen_data.blueprints as _blueprints' imported but unused*

`cfme/tests/test_db_migrate.py`:
- :red_circle: Line 7:1: **F401** *'cfme.utils.conf' imported but unused*

`cfme/utils/browser.py`:
- :red_circle: Line 7:1: **F401** *'warnings' imported but unused*

`cfme/utils/version.py`:
- :red_circle: Line 6:1: **F401** *'miq_version.LATEST' imported but unused*
- :red_circle: Line 7:1: **F401** *'miq_version.LOWEST' imported but unused*
- :red_circle: Line 8:1: **F401** *'miq_version.SPTuple' imported but unused*
- :red_circle: Line 9:1: **F401** *'miq_version.UPSTREAM' imported but unused*
- :red_circle: Line 11:1: **F401** *'miq_version.version_stream_product_mapping' imported but unused*

`cfme/utils/wait.py`:
- :red_circle: Line 3:1: **F401** *'wait_for.RefreshTimer' imported but unused*
- :red_circle: Line 4:1: **F401** *'wait_for.TimedOutError' imported but unused*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f31ba85c8b5c91854a5975e3671b4dc5860fcf67:

`cfme/fixtures/appliance.py`:
- :red_circle: Line 18:1: **F401** *'cfme.utils.version.get_stream' imported but unused*

`cfme/infrastructure/virtual_machines.py`:
- :red_circle: Line 22:1: **F401** *'widgetastic_patternfly.BootstrapNav' imported but unused*

`cfme/services/service_catalogs/ssui.py`:
- :red_circle: Line 6:1: **F401** *'widgetastic_patternfly.BootstrapSelect' imported but unused*
- :red_circle: Line 8:1: **F401** *'widgetastic_patternfly.Input' imported but unused*

`cfme/storage/volume_type.py`:
- :red_circle: Line 4:1: **F401** *'navmazing.NavigateToSibling' imported but unused*
- :red_circle: Line 5:1: **F401** *'widgetastic.widget.NoSuchElementException' imported but unused*

`cfme/tests/cloud/test_providers.py`:
- :red_circle: Line 20:1: **F401** *'cfme.common.provider_views.CloudProvidersDiscoverView' imported but unused*
- :red_circle: Line 31:1: **F401** *'cfme.utils.rest.delete_resources_from_collection' imported but unused*
- :red_circle: Line 32:1: **F401** *'cfme.utils.rest.delete_resources_from_detail' imported but unused*

`cfme/tests/configure/test_log_depot_operation.py`:
- :red_circle: Line 9:1: **F401** *'datetime.timedelta' imported but unused*

`cfme/tests/configure/test_schedule_operations.py`:
- :red_circle: Line 10:1: **F401** *'cfme.utils.conf' imported but unused*

`cfme/tests/containers/test_alerts.py`:
- :red_circle: Line 6:1: **F401** *'cfme.utils.version.current_version' imported but unused*

`cfme/tests/infrastructure/test_pxe_provisioning.py`:
- :red_circle: Line 13:1: **F401** *'cfme.utils.blockers.BZ' imported but unused*
- :red_circle: Line 14:1: **F401** *'cfme.utils.blockers.GH' imported but unused*

`cfme/tests/openstack/cloud/test_volumes.py`:
- :red_circle: Line 10:1: **F401** *'cfme.utils.wait.wait_for' imported but unused*

`cfme/tests/openstack/infrastructure/test_hosts.py`:
- :red_circle: Line 5:1: **F401** *'cfme.utils.appliance.implementations.ui.navigator' imported but unused*

`cfme/tests/services/test_rest_services.py`:
- :red_circle: Line 13:1: **F401** *'cfme.rest.gen_data.blueprints as _blueprints' imported but unused*

`cfme/tests/test_db_migrate.py`:
- :red_circle: Line 7:1: **F401** *'cfme.utils.conf' imported but unused*

`cfme/utils/browser.py`:
- :red_circle: Line 7:1: **F401** *'warnings' imported but unused*

`cfme/utils/version.py`:
- :red_circle: Line 6:1: **F401** *'miq_version.LATEST' imported but unused*
- :red_circle: Line 7:1: **F401** *'miq_version.LOWEST' imported but unused*
- :red_circle: Line 8:1: **F401** *'miq_version.SPTuple' imported but unused*
- :red_circle: Line 9:1: **F401** *'miq_version.UPSTREAM' imported but unused*
- :red_circle: Line 11:1: **F401** *'miq_version.version_stream_product_mapping' imported but unused*

`cfme/utils/wait.py`:
- :red_circle: Line 3:1: **F401** *'wait_for.RefreshTimer' imported but unused*
- :red_circle: Line 4:1: **F401** *'wait_for.TimedOutError' imported but unused*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit dfb78ba51b44e1d4f3de34ccc791a6c31f67ad14:

`cfme/tests/configure/test_log_depot_operation.py`:
- :red_circle: Line 9:1: **F401** *'datetime.timedelta' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mshriver** [comment]
@valaparthvi I agree about the readability, but we are not applying black to the entire repository yet. When we do, maybe we can drop this hook completely and just let black order the imports.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by jawatts** [comment]
:+1:
